FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

# RUN apt-get update && apt-get install -y pip
# RUN pip3 install flask

COPY ./bin/server /server
COPY ./bin/libgomp.so.1 /usr/lib/x86_64-linux-gnu/libgomp.so.1

RUN mkdir /opt/ || echo "Directory already exists"
COPY ./dev/proxy_server.py /opt/proxy_server.py
COPY ./dev/proxy.json /opt/proxy.json

RUN apt-get clean &&  rm -rf /var/lib/apt/lists/* && rm -rf /root/.cache/pip

ENTRYPOINT ["/server"]